### ISSUE TITLE
[BUG] - Ctl+d causes error

### ISSUE THREAD

**Issue by scottbarrow** [nguyenquangminh0711/ruby_jard#34]
**Describe the bug**
Using ctrl-d (pry continue command) causes error

**To Reproduce**
1: add jard to a file
2: enter ctrl+d 
**Expected behavior**
Program to continue 

**Screenshots**
```
Control command is empty
/Users/scott/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby_jard-0.3.0/lib/ruby_jard/control_flow.rb:33:in `validate!'
/Users/scott/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby_jard-0.3.0/lib/ruby_jard/control_flow.rb:28:in `initialize'
/Users/scott/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby_jard-0.3.0/lib/ruby_jard/control_flow.rb:53:in `new'
/Users/scott/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby_jard-0.3.0/lib/ruby_jard/control_flow.rb:53:in `dispatch'
/Users/scott/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby_jard-0.3.0/lib/ruby_jard/repl_proxy.rb:169:in `rescue in repl'
/Users/scott/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby_jard-0.3.0/lib/ruby_jard/repl_proxy.rb:166:in `repl'
/Users/scott/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby_jard-0.3.0/lib/ruby_jard/repl_processor.rb:70:in `block in process_commands'
```

**Comment by nguyenquangminh0711** [comment]
@scottbarrow This bug is fixed in https://github.com/nguyenquangminh0711/ruby_jard/pull/36, and will be available in next release. In a mean time, you can use jard from `master` branch, or that specific commit:

```ruby
gem 'ruby_jard', group: :development, git: 'https://github.com/nguyenquangminh0711/ruby_jard'
# or
gem 'ruby_jard', group: :development, git: 'https://github.com/nguyenquangminh0711/ruby_jard', ref: '13455f2813f8820e0be502552cbf6fd312b4a396'
```

I'll close this issue when a new version is released.

**Comment by scottbarrow** [comment]
Thanks for the fast turnaround
