### ISSUE TITLE
[BUG] Internal error from jard - undefined method `shift` for nil

### ISSUE THREAD

**Issue by feliperaul** [nguyenquangminh0711/ruby_jard#54]
**Describe the bug**

Using jard and it printed this message in my console. Jard worked fine tough:

```
jard >> --- Error ---
rails     | Internal error from Jard. I'm sorry to mess up your debugging experience.
rails     | It would be great if you can submit an issue in https://github.com/nguyenquangminh0711/ruby_jard/issues
rails     |
rails     | undefined method `shift' for nil:NilClass
rails     | /Users/dev/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/ruby_jard-cbba19ba3354/lib/ruby_jard/decorators/color_decorator.rb:46:in `decorate'
rails     | /Users/dev/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/ruby_jard-cbba19ba3354/lib/ruby_jard/row_renderer.rb:108:in `block in generate_bitmap'
rails     | /Users/dev/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/ruby_jard-cbba19ba3354/lib/ruby_jard/row_renderer.rb:96:in `each'
rails     | /Users/dev/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/ruby_jard-cbba19ba3354/lib/ruby_jard/row_renderer.rb:96:in `generate_bitmap'
rails     | /Users/dev/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/ruby_jard-cbba19ba3354/lib/ruby_jard/row_renderer.rb:40:in `render'
rails     | /Users/dev/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/ruby_jard-cbba19ba3354/lib/ruby_jard/screen_renderer.rb:146:in `row_content'
rails     | /Users/dev/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/ruby_jard-cbba19ba3354/lib/ruby_jard/screen_renderer.rb:105:in `block in find_seleted_window'
rails     | /Users/dev/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/ruby_jard-cbba19ba3354/lib/ruby_jard/screen_renderer.rb:104:in `each'
rails     | /Users/dev/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/ruby_jard-cbba19ba3354/lib/ruby_jard/screen_renderer.rb:104:in `each_with_index'
rails     | /Users/dev/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/ruby_jard-cbba19ba3354/lib/ruby_jard/screen_renderer.rb:104:in `find_seleted_window'
rails     | -------------
```

Environment (please complete the following information):

OS: MacOs Catalina 10.15.6
iTerm2 (tested with and without Overmind)
Output when you run tput colors in your terminal: 256
Output when you run echo $TERM in your terminal: xterm-256color
Output when you run stty:
speed 38400 baud;
lflags: echoe echok echoke echoctl pendin
iflags: iutf8
oflags: -oxtabs
cflags: cs8 -parenb
Do you use tmux/screen or similar tty multiplexer?: I use Overmind, but I tested with a vanilla rails s in a new tab and it happens just the same

**Comment by nguyenquangminh0711** [comment]
Hi @feliperaul, thanks for reporting again. This bug is handled in #56. You can try the fix at master branch first. I'll push a relase soon.

```ruby
gem 'ruby_jard', git: 'https://github.com/nguyenquangminh0711/ruby_jard', ref: 'master'
```
