### ISSUE TITLE
Breakpoint in initializer throws error "undefined method `to_hash' for nil:NilClass"

### ISSUE THREAD

**Issue by hlascelles** [nguyenquangminh0711/ruby_jard#65]
**The bug**

Putting `jard` in an `ActiveRecord` model `initializer` causes an error as it is trying to call `to_hash` on `nil`.

**To Reproduce**

Run this code:

```
class Foo < ApplicationRecord
  def initialize(attrs = {})
    jard
    puts "Bang!"
  end
end
```

**Expected behavior**

It should know about being in an initializer and not error.

**Stacktrace**

```
undefined method `to_hash' for nil:NilClass
gems/activerecord-5.2.4.4/lib/active_record/attribute_methods.rb:327:in `attributes'
gems/ruby_jard-0.3.1/lib/ruby_jard/decorators/rails_decorator.rb:36:in `decorate_singleline'
gems/ruby_jard-0.3.1/lib/ruby_jard/decorators/rails_decorator.rb:44:in `decorate_multiline'
gems/ruby_jard-0.3.1/lib/ruby_jard/decorators/rails_decorator.rb:187:in `block in decorate_multiline'
gems/ruby_jard-0.3.1/lib/ruby_jard/decorators/rails_decorator.rb:184:in `each'
gems/ruby_jard-0.3.1/lib/ruby_jard/decorators/rails_decorator.rb:184:in `decorate_multiline'
gems/ruby_jard-0.3.1/lib/ruby_jard/decorators/inspection_decorator.rb:73:in `block in decorate_multiline'
gems/ruby_jard-0.3.1/lib/ruby_jard/decorators/inspection_decorator.rb:70:in `each'
gems/ruby_jard-0.3.1/lib/ruby_jard/decorators/inspection_decorator.rb:70:in `decorate_multiline'
gems/ruby_jard-0.3.1/lib/ruby_jard/screens/variables_screen.rb:70:in `block in build'
```

**Environment**
All

Thank you for this excellent utility!

**Comment by nguyenquangminh0711** [comment]
Hi @hlascelles, thanks for your report. I created a PR to fix this issue, and already merged into master branch. You can try the fix at master branch first. I'll push a relase soon.

```ruby
gem 'ruby_jard', git: 'https://github.com/nguyenquangminh0711/ruby_jard', ref: 'master'
```
